#!/usr/bin/env python3
"""Regenerate the hash-locked Python requirements of the training stacks.

    python backend/scripts/lock_training.py            # every stack
    python backend/scripts/lock_training.py hf-cu129   # one stack

Needs network access and uv (pip install uv). Nothing here runs at build time:
the locks are committed, and an image build installs exactly what they name.

Each stack directory holds base.in plus one <addon>.in per optional add-on.
Add-ons can be combined freely, so they must agree with each other as well as
with the base. To guarantee that, the script first resolves everything at once
(all.lock), then resolves the base and each add-on again constrained to those
versions. Any combination of the resulting files is therefore a subset of one
consistent resolution, and merging them can never produce two versions of a
package.

The target is fixed: CPython 3.12 on x86_64 glibc 2.39 (Ubuntu 24.04), which is
what every stack's base image provides.
"""

import json
import re
import subprocess
import urllib.request
import sys
import tempfile
from pathlib import Path

STACKS = Path(__file__).resolve().parent.parent / "layersmith" / "training" / "stacks"
PYTHON_VERSION = "3.12"
PLATFORM = "x86_64-manylinux_2_39"

# Packages published only as a source archive whose setup.py imports torch, so
# a resolver cannot build them to read their dependencies. Their declared
# dependencies (from PyPI's JSON API, same version) are given here instead.
DEPENDENCY_METADATA = """
[[dependency-metadata]]
name = "deepspeed"
version = "0.19.7"
requires-dist = ["einops", "hjson", "msgpack", "ninja", "numpy", "packaging>=20.0", "psutil",
                 "py-cpuinfo", "pydantic>=2.0.0", "torch>=2.0.0", "tqdm"]
"""

NAME_RE = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)(?:\[[^\]]*\])?\s*(==|@)")


def normalise(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def compile_requirements(inputs: list[Path], output: Path, constraints: Path | None, config: Path) -> None:
    argv = ["uv", "pip", "compile", "--quiet", "--generate-hashes", "--no-header", "--no-annotate",
            "--python-version", PYTHON_VERSION, "--python-platform", PLATFORM,
            "--config-file", str(config), "--output-file", str(output), *map(str, inputs)]
    if constraints is not None:
        argv += ["--constraint", str(constraints)]
    subprocess.run(argv, check=True)


def blocks(lock_text: str) -> dict[str, str]:
    """Package name -> its full requirement block (pin plus hash lines)."""
    found, current, lines = {}, None, []
    for line in lock_text.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if not line.startswith((" ", "\t")):
            if current:
                found[current] = "\n".join(lines)
            match = NAME_RE.match(line)
            if not match:
                raise SystemExit(f"Unrecognised lock line: {line}")
            current, lines = normalise(match.group(1)), [line]
        else:
            lines.append(line)
    if current:
        found[current] = "\n".join(lines)
    return found


def pins(lock_text: str) -> str:
    """A constraints file: the first line of each block, without hashes."""
    return "\n".join(block.splitlines()[0].rstrip(" \\") for block in blocks(lock_text).values()) + "\n"


def has_wheel(name: str, version: str) -> bool:
    """Whether PyPI has a wheel for this release that installs on the target platform."""
    with urllib.request.urlopen(f"https://pypi.org/pypi/{name}/{version}/json", timeout=60) as response:
        files = json.load(response)["urls"]
    for item in files:
        filename = item["filename"]
        if not filename.endswith(".whl"):
            continue
        tags = filename[:-4].split("-")[-3:]
        python, abi, platform = tags
        if platform == "any" or ("x86_64" in platform and "linux" in platform
                                 and (python in ("cp312", "py3") or abi == "abi3")):
            return True
    return False


def record_source_builds(stack: Path) -> None:
    """source-builds.txt: locked packages that only exist as a source archive.

    An image installs everything else with --only-binary, then builds these
    with --no-build-isolation against the packages already installed (their
    build scripts import torch, for instance).
    """
    sources = []
    for lock in sorted(stack.glob("*.lock")):
        for name, block in blocks(lock.read_text()).items():
            first = block.splitlines()[0]
            if "==" in first and not has_wheel(name, first.split("==", 1)[1].split()[0]):
                sources.append(name)
    (stack / "source-builds.txt").write_text(
        "# Locked packages without a usable wheel; built from source at image build time.\n"
        "# Generated by backend/scripts/lock_training.py - do not edit.\n" + "".join(f"{n}\n" for n in sorted(set(sources))))
    print(f"{stack.name}: source builds {sorted(set(sources)) or 'none'}", flush=True)


def lock_stack(stack: Path, config: Path) -> None:
    addons = sorted(p for p in stack.glob("*.in") if p.stem != "base")
    base_in = stack / "base.in"
    all_lock = stack / "all.lock"
    print(f"{stack.name}: resolving base + {[a.stem for a in addons]}", flush=True)
    compile_requirements([base_in, *addons], all_lock, None, config)

    with tempfile.TemporaryDirectory() as tmp:
        constraints = Path(tmp) / "constraints.txt"
        constraints.write_text(pins(all_lock.read_text()))

        base_lock = stack / "base.lock"
        compile_requirements([base_in], base_lock, constraints, config)
        base_blocks = blocks(base_lock.read_text())

        for addon in addons:
            combined = Path(tmp) / f"{addon.stem}.lock"
            compile_requirements([base_in, addon], combined, constraints, config)
            extra = {name: block for name, block in blocks(combined.read_text()).items() if name not in base_blocks}
            header = (f"# Add-on '{addon.stem}' for stack {stack.name}: packages beyond base.lock.\n"
                      "# Generated by backend/scripts/lock_training.py - do not edit.\n")
            (stack / f"{addon.stem}.lock").write_text(header + "\n".join(extra.values()) + "\n")

    header = f"# Stack {stack.name}: base packages.\n# Generated by backend/scripts/lock_training.py - do not edit.\n"
    base_lock.write_text(header + base_lock.read_text())
    all_lock.unlink()  # only an intermediate; the per-component locks are what builds use
    print(f"{stack.name}: base {len(base_blocks)} packages", flush=True)
    record_source_builds(stack)


def main(names: list[str]) -> None:
    if names[:1] == ["--sources-only"]:
        for stack in sorted(p for p in STACKS.iterdir() if p.is_dir()):
            if not names[1:] or stack.name in names[1:]:
                record_source_builds(stack)
        return
    with tempfile.NamedTemporaryFile("w", suffix=".toml", delete=False) as handle:
        handle.write(DEPENDENCY_METADATA)
        config = Path(handle.name)
    try:
        for stack in sorted(p for p in STACKS.iterdir() if p.is_dir()):
            if not names or stack.name in names:
                lock_stack(stack, config)
    finally:
        config.unlink()


if __name__ == "__main__":
    main(sys.argv[1:])
