"""Containerfile generation (GUI mode) and parsing (Advanced/import mode).

GUI mode owns the file: it is regenerated from the specification on every
save, so hand edits belong in Advanced mode, where LayerSmith stores the text
as given and only reads it to find the base image.

The base is pinned by digest when one is known, so a rebuild of the same
version produces the same layers instead of silently following a moved tag.
"""

import re

from layersmith.core import catalog
from layersmith.core.spec import resolve_packages

SHARE_DIR = "/usr/local/share/layersmith"
ENTRYPOINT_PATH = "/usr/local/bin/layersmith-entrypoint.sh"

FROM_RE = re.compile(r"^\s*FROM\s+(?:--platform=\S+\s+)?(\S+)(?:\s+AS\s+(\S+))?\s*$", re.I | re.M)


def _quote(value):
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$") + '"'


def _install(family, packages, epel=False):
    """One RUN line that installs packages and cleans the package cache."""
    if not packages:
        return None
    joined = " \\\n    ".join(packages)
    if family == "rpm":
        prefix = "dnf install -y epel-release && " if epel else ""
        return (f"RUN {prefix}dnf install -y --setopt=install_weak_deps=False \\\n"
                f"    {joined} \\\n    && dnf clean all")
    if family == "deb":
        return ("RUN apt-get update \\\n"
                "    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \\\n"
                f"    {joined} \\\n    && rm -rf /var/lib/apt/lists/*")
    return f"RUN apk add --no-cache \\\n    {joined}"


def script_body(text):
    text = (text or "").replace("\r\n", "\n")
    return text if text.startswith("#!") else "#!/bin/sh\nset -eu\n" + text


def context_plan(spec):
    """Files the build context must contain: [(context path, kind, source)]."""
    plan = []
    for tool in spec.get("tools") or []:
        plan.append((f"tools/{tool['sha256']}", "blob", tool["sha256"]))
    for item in spec.get("files") or []:
        plan.append((f"files/{item['sha256']}", "blob", item["sha256"]))
    for key, text in (spec.get("scripts") or {}).items():
        if text and text.strip():
            plan.append((f"scripts/{key.replace('_', '-')}.sh", "script", key))
    return plan


def generate(project, spec, base_digest=None):
    """Return (containerfile_text, packages, warnings) for a GUI-mode project."""
    family = spec["base"]["family"]
    base = spec["base"]["source"]
    repository = base.split("@", 1)[0].rsplit(":", 1)[0]
    packages, warnings = resolve_packages(spec)
    scripts = {k: v for k, v in (spec.get("scripts") or {}).items() if v and v.strip()}
    el = catalog.DISTROS.get(spec["base"].get("distribution"), {}).get("el", False)

    lines = [
        f"# Generated by LayerSmith for project {project['name']}.",
        "# GUI managed: this file is regenerated on save. Switch to Advanced mode to edit it yourself.",
        f"FROM {repository}@{base_digest}" if base_digest else f"FROM {base}",
        "",
    ]

    labels = {
        "org.opencontainers.image.title": project["name"],
        "org.opencontainers.image.description": (project.get("description") or "")[:200].replace("\n", " "),
        "org.opencontainers.image.base.name": base,
        **(spec.get("labels") or {}),
    }
    if base_digest:
        labels["org.opencontainers.image.base.digest"] = base_digest
    lines.append("LABEL " + " \\\n      ".join(f"{k}={_quote(v)}" for k, v in labels.items()))

    if scripts.get("pre_build"):
        lines += ["", f"COPY --chmod=0755 scripts/pre-build.sh {SHARE_DIR}/pre-build.sh",
                  f"RUN {SHARE_DIR}/pre-build.sh"]

    install = _install(family, packages, epel=bool(spec.get("enable_epel")) and el)
    if install:
        lines += ["", install]

    for tool in spec.get("tools") or []:
        lines.append(f"COPY --chmod={tool['mode']} tools/{tool['sha256']} {tool['install_path']}")
    for item in spec.get("files") or []:
        lines.append(f"COPY --chmod={item['mode']} files/{item['sha256']} {item['destination']}")

    if spec.get("env"):
        lines += ["", "ENV " + " \\\n    ".join(f"{e['name']}={_quote(e['value'])}" for e in spec["env"])]

    if scripts.get("post_install"):
        lines += ["", f"COPY --chmod=0755 scripts/post-install.sh {SHARE_DIR}/post-install.sh",
                  f"RUN {SHARE_DIR}/post-install.sh"]

    user = spec.get("user") or {}
    if user.get("name"):
        lines.append("")
        if user.get("gid"):
            gid = int(user["gid"])
            lines.append(f"RUN groupadd -g {gid} {user['name']} || addgroup -g {gid} {user['name']}")
        opts = " ".join(filter(None, [f"-u {int(user['uid'])}" if user.get("uid") else "",
                                      f"-g {int(user['gid'])}" if user.get("gid") else ""]))
        lines.append(f"RUN useradd -m -s {user['shell']} {opts} {user['name']} "
                     f"|| adduser -D -s {user['shell']} {user['name']}")

    if spec.get("workdir"):
        lines += ["", f"WORKDIR {spec['workdir']}"]
    if user.get("name"):
        lines.append(f"USER {user['name']}")

    if scripts.get("entrypoint"):
        lines += ["", f"COPY --chmod=0755 scripts/entrypoint.sh {ENTRYPOINT_PATH}",
                  f'ENTRYPOINT ["{ENTRYPOINT_PATH}"]']

    return "\n".join(lines) + "\n", packages, warnings


def bases(text):
    """External base images a Containerfile starts from (build stages excluded)."""
    stages, found = set(), []
    for match in FROM_RE.finditer(text or ""):
        reference, alias = match.group(1), match.group(2)
        if reference.lower() != "scratch" and reference not in stages and "$" not in reference:
            found.append(reference)
        if alias:
            stages.add(alias)
    return found
