import pytest
from fastapi.testclient import TestClient

from layersmith import config
from layersmith.api import create_app
from layersmith.models import Build
from tests.test_builds import DIGEST, FakeBackend


@pytest.fixture
def client(tmp_path):
    settings = config.reset_for_tests(
        data_dir=tmp_path, image_dir=tmp_path / "images", build_dir=tmp_path / "builds",
        upload_dir=tmp_path / "uploads", log_dir=tmp_path / "logs", tmp_dir=tmp_path / "tmp",
        database_url=f"sqlite:///{tmp_path}/test.db",
    )
    app = create_app(settings)
    service = app.state.layersmith["build_service"]
    service.backend = FakeBackend()
    # Tests drive builds through run_pending_build() so assertions are not
    # racing the background worker; the queue itself is covered in
    # test_builds.py::test_queued_build_runs_in_the_background_worker.
    service.enqueue = lambda build_id: None
    with TestClient(app) as test_client:
        test_client.state = app.state.layersmith
        yield test_client


def run_pending_build(client, build_id):
    """Run the queued build synchronously so tests stay deterministic."""
    client.state["build_service"].run(build_id)


def test_catalog_exposes_templates_and_distributions(client):
    catalog = client.get("/api/catalog").json()
    names = [t["name"] for t in catalog["templates"]]
    assert {"Developer", "Linux Admin", "Network Tools", "Ansible", "Kubernetes", "Minimal"} <= set(names)
    assert any(d["name"] == "AlmaLinux" and d["family"] == "rpm" for d in catalog["distributions"])
    assert catalog["architectures"] == ["amd64", "arm64"]


def test_preview_returns_containerfile_without_storing_anything(client):
    response = client.post("/api/preview", json={
        "name": "network-tools", "template": "Network Tools",
        "spec": {"base": {"distribution": "Ubuntu", "version": "24.04"}}})
    body = response.json()
    assert response.status_code == 200
    assert "apt-get install" in body["containerfile"] and "dnsutils" in body["packages"]
    assert client.get("/api/projects").json() == []


def test_full_workflow_from_wizard_to_airgap(client):
    created = client.post("/api/projects", json={
        "name": "network-tools", "description": "Packet tools", "template": "Network Tools",
        "spec": {"base": {"distribution": "AlmaLinux", "version": "10"}}}).json()
    assert created["repository"] == "layersmith/network-tools"

    detail = client.get(f"/api/projects/{created['id']}").json()
    assert "bind-utils" in detail["packages"] and detail["containerfile"].startswith("# Generated by LayerSmith")

    started = client.post(f"/api/projects/{created['id']}/builds", json={}).json()
    assert started["status"] == "queued" and started["version"] == "1.0.0"
    assert started["image_ref"] == "layersmith/network-tools:1.0.0"
    run_pending_build(client, started["id"])

    build = client.get(f"/api/builds/{started['id']}").json()
    assert build["status"] == "ready" and build["base_digest"] == DIGEST
    assert build["manifest"]["packages"] and build["manifest"]["build"] == build["number"]
    assert "STEP 1/2" in build["log"]

    bundle = client.post(f"/api/builds/{started['id']}/airgap", json={})
    assert bundle.status_code == 201 and bundle.json()["filename"].endswith("-airgap.tar.gz")

    for kind in ("export", "airgap"):
        download = client.get(f"/api/builds/{started['id']}/download/{kind}")
        assert download.status_code == 200 and download.content

    stats = client.get("/api/stats").json()
    assert stats["projects"] == 1 and stats["images"] == 1 and stats["recent"][0]["project_name"] == "network-tools"


def test_next_version_advances_and_versions_are_never_rebuilt(client):
    project = client.post("/api/projects", json={
        "name": "app", "template": "Minimal", "spec": {"base": {"distribution": "Alpine", "version": "3.22"}}}).json()
    first = client.post(f"/api/projects/{project['id']}/builds", json={}).json()
    run_pending_build(client, first["id"])

    assert client.get(f"/api/projects/{project['id']}").json()["next_version"] == "1.0.1"
    again = client.post(f"/api/projects/{project['id']}/builds", json={"version": "1.0.0"})
    assert again.status_code == 409 and "never overwritten" in again.json()["detail"]

    second = client.post(f"/api/projects/{project['id']}/builds", json={}).json()
    assert second["version"] == "1.0.1" and second["number"] == first["number"] + 1


def test_import_containerfile_creates_an_advanced_project(client):
    text = "FROM alpine:3.22\nRUN apk add --no-cache git curl\n"
    project = client.post("/api/projects/import", json={"name": "imported", "containerfile": text}).json()
    assert project["mode"] == "advanced" and project["base_image"] == "alpine:3.22"

    build = client.post(f"/api/projects/{project['id']}/builds", json={}).json()
    run_pending_build(client, build["id"])
    assert client.get(f"/api/builds/{build['id']}").json()["containerfile"] == text


def test_import_without_from_is_rejected(client):
    response = client.post("/api/projects/import", json={"name": "bad", "containerfile": "RUN echo hi"})
    assert response.status_code == 422 and "FROM" in response.json()["detail"]


def test_clone_copies_the_definition_but_not_the_builds(client):
    project = client.post("/api/projects", json={
        "name": "network-tools", "template": "Network Tools",
        "spec": {"base": {"distribution": "AlmaLinux", "version": "10"}}}).json()
    build = client.post(f"/api/projects/{project['id']}/builds", json={}).json()
    run_pending_build(client, build["id"])

    clone = client.post(f"/api/projects/{project['id']}/clone", json={"name": "network-tools-custom"}).json()
    assert clone["spec"] == project["spec"] and clone["repository"] == "layersmith/network-tools-custom"
    assert client.get(f"/api/projects/{clone['id']}").json()["builds"] == []


def test_invalid_input_is_rejected_with_a_message(client):
    bad_name = client.post("/api/projects", json={"name": "Not A Valid Name", "template": "Minimal",
                                                  "spec": {"base": {"distribution": "Alpine", "version": "3.22"}}})
    assert bad_name.status_code == 422

    secret = client.post("/api/preview", json={"name": "x", "template": "Minimal", "spec": {
        "base": {"distribution": "Alpine", "version": "3.22"},
        "env": [{"name": "REGISTRY_TOKEN", "value": "abc"}]}})
    assert secret.status_code == 422 and "runtime" in secret.json()["detail"]


def test_duplicate_project_names_are_refused(client):
    payload = {"name": "dup", "template": "Minimal", "spec": {"base": {"distribution": "Alpine", "version": "3.22"}}}
    assert client.post("/api/projects", json=payload).status_code == 201
    assert client.post("/api/projects", json=payload).status_code == 409


def test_upload_is_content_addressed(client):
    first = client.post("/api/uploads", files={"file": ("config.yml", b"key: value")}).json()
    second = client.post("/api/uploads", files={"file": ("other-name.yml", b"key: value")}).json()
    assert first["sha256"] == second["sha256"] and first["size"] == len(b"key: value")
    assert (client.state["settings"].upload_dir / first["sha256"]).read_bytes() == b"key: value"


def test_download_refuses_paths_outside_the_image_directory(client):
    project = client.post("/api/projects", json={
        "name": "app", "template": "Minimal", "spec": {"base": {"distribution": "Alpine", "version": "3.22"}}}).json()
    build = client.post(f"/api/projects/{project['id']}/builds", json={}).json()
    run_pending_build(client, build["id"])

    with client.state["session_factory"]() as session:
        row = session.get(Build, build["id"])
        row.export_path = "/etc/passwd"
        session.commit()
    assert client.get(f"/api/builds/{build['id']}/download/export").status_code == 404


def test_settings_reports_paths_and_backend_state(client):
    body = client.get("/api/settings").json()
    assert body["app_name"] == "LayerSmith" and body["tagline"]
    fields = {row["field"] for row in body["paths"]}
    assert fields == {"data_dir", "image_dir", "build_dir", "upload_dir", "log_dir", "tmp_dir"}
    # The data directory holds the database, so it is never editable here.
    assert [row["editable"] for row in body["paths"] if row["field"] == "data_dir"] == [False]
    assert all(row["path"].startswith("/") for row in body["paths"])
    assert body["storage"]["total"] > 0 and "available" in body["build_backend"]


def test_build_log_websocket_replays_then_closes_for_finished_builds(client):
    project = client.post("/api/projects", json={
        "name": "app", "template": "Minimal", "spec": {"base": {"distribution": "Alpine", "version": "3.22"}}}).json()
    build = client.post(f"/api/projects/{project['id']}/builds", json={}).json()
    run_pending_build(client, build["id"])

    with client.websocket_connect(f"/api/builds/{build['id']}/logs") as websocket:
        messages = [websocket.receive_json() for _ in range(3)]
    assert messages[0]["type"] == "log" and "LayerSmith" in messages[0]["line"]
